AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Despliegue de API FastAPI con AWS Lambda y API Gateway HTTP API

Parameters:
  StageName:
    Type: String
    Default: v1
    Description: Nombre del stage de API Gateway (v1, prod, dev)

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    Environment:
      Variables:
        STAGE: !Ref StageName

Resources:
  # Función Lambda para FastAPI
  FastAPIAppLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub fastapi-app-${StageName}
      CodeUri: ./app
      Handler: app.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref FastAPIHttpApi
            Path: /{proxy+}
            Method: ANY

  # API Gateway HTTP API
  FastAPIHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      FailOnWarnings: true
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: !Sub FastAPI Application - ${StageName}
          version: '1.0.0'
        paths:
          /:
            get:
              responses:
                '200':
                  description: OK
              x-amazon-apigateway-integration:
                payloadFormatVersion: "2.0"
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FastAPIAppLambda.Arn}/invocations
          /{proxy+}:
            x-amazon-apigateway-any-method:
              responses:
                '200':
                  description: OK
              x-amazon-apigateway-integration:
                payloadFormatVersion: "2.0"
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FastAPIAppLambda.Arn}/invocations
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowOrigins:
          - "*"
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Amz-Date
          - X-Api-Key
          - X-Amz-Security-Token

  # Permiso para que API Gateway invoque Lambda
  ApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt FastAPIAppLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FastAPIHttpApi}/*/*/*

Outputs:
  ApiUrl:
    Description: URL del API Gateway
    Value: !Sub https://${FastAPIHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/
  LambdaFunctionName:
    Description: Nombre de la función Lambda
    Value: !Ref FastAPIAppLambda